(function (exports) {
 exports.iso_3166_country_names_de = {
	  'AD':'Andorra'
	, 'AE':'Vereinigte Arabische Emirate'
	, 'AF':'Afghanistan'
	, 'AG':'Antigua und Barbuda'
	, 'AI':'Anguilla'
	, 'AL':'Albanien'
	, 'AM':'Armenien'
	, 'AO':'Angola'
	, 'AQ':'Antarktis'
	, 'AR':'Argentinien'
	, 'AS':'Amerikanisch-Samoa'
	, 'AT':'Ãsterreich'
	, 'AU':'Australien'
	, 'AW':'Aruba'
	, 'AX':'Ãlandinseln'
	, 'AZ':'Aserbaidschan'
	, 'BA':'Bosnien und Herzegowina'
	, 'BB':'Barbados'
	, 'BD':'Bangladesch'
	, 'BE':'Belgien'
	, 'BF':'Burkina Faso'
	, 'BG':'Bulgarien'
	, 'BH':'Bahrain'
	, 'BI':'Burundi'
	, 'BJ':'Benin'
	, 'BL':'St. BarthÃ©lemy'
	, 'BM':'Bermuda'
	, 'BN':'Brunei Darussalam'
	, 'BO':'Bolivien'
	, 'BR':'Brasilien'
	, 'BS':'Bahamas'
	, 'BT':'Bhutan'
	, 'BV':'Bouvetinsel'
	, 'BW':'Botsuana'
	, 'BY':'Belarus'
	, 'BZ':'Belize'
	, 'CA':'Kanada'
	, 'CC':'Kokosinseln'
	, 'CD':'Demokratische Republik Kongo'
	, 'CF':'Zentralafrikanische Republik'
	, 'CG':'Republik Kongo'
	, 'CH':'Schweiz'
	, 'CI':'CÃ´te dâIvoire'
	, 'CK':'Cookinseln'
	, 'CL':'Chile'
	, 'CM':'Kamerun'
	, 'CN':'China'
	, 'CO':'Kolumbien'
	, 'CP':'Clipperton'
	, 'CR':'Costa Rica'
	, 'CU':'Kuba'
	, 'CV':'Kap Verde'
	, 'CX':'Weihnachtsinsel'
	, 'CW':'CuraÃ§ao'
	, 'CY':'Zypern'
	, 'CZ':'Tschechische Republik'
	, 'DE':'Deutschland'
	, 'DJ':'Dschibuti'
	, 'DK':'DÃ¤nemark'
	, 'DM':'Dominica'
	, 'DO':'Dominikanische Republik'
	, 'DZ':'Algerien'
	, 'EC':'Ecuador'
	, 'EE':'Estland'
	, 'EG':'Ãgypten'
	, 'EH':'Westsahara'
	, 'EL':'Griechenland'
	, 'ER':'Eritrea'
	, 'ES':'Spanien'
	, 'ET':'Ãthiopien'
	, 'FI':'Finnland'
	, 'FJ':'Fidschi'
	, 'FK':'Falklandinseln (Malwinen)'
	, 'FM':'Mikronesien'
	, 'FO':'FÃ¤rÃ¶er'
	, 'FR':'Frankreich'
	, '(noch festzulegen)':'ehemalige jugoslawische Republik Mazedonien'
	, 'GA':'Gabun'
	, 'GD':'Grenada'
	, 'GE':'Georgien'
	, 'GF':'FranzÃ¶sisch-Guayana'
	, 'GG':'Guernsey'
	, 'GH':'Ghana'
	, 'GI':'Gibraltar'
	, 'GL':'GrÃ¶nland'
	, 'GM':'Gambia'
	, 'GN':'Guinea'
	, 'GP':'Guadeloupe'
	, 'GQ':'Ãquatorialguinea'
	, 'GS':'SÃ¼dgeorgien und die SÃ¼dlichen Sandwichinseln'
	, 'GT':'Guatemala'
	, 'GU':'Guam'
	, 'GW':'Guinea-Bissau'
	, 'GY':'Guyana'
	, 'HK':'Hongkong'
	, 'HM':'Heard und die McDonaldinseln'
	, 'HN':'Honduras'
	, 'HR':'Kroatien'
	, 'HT':'Haiti'
	, 'HU':'Ungarn'
	, 'ID':'Indonesien'
	, 'IE':'Irland'
	, 'IL':'Israel'
	, 'IM':'Insel Man'
	, 'IN':'Indien'
	, 'IO':'Britisches Territorium im Indischen Ozean'
	, 'IQ':'Irak'
	, 'IR':'Iran'
	, 'IS':'Island'
	, 'IT':'Italien'
	, 'JE':'Jersey'
	, 'JM':'Jamaika'
	, 'JO':'Jordanien'
	, 'JP':'Japan'
	, 'KE':'Kenia'
	, 'KG':'Kirgisistan'
	, 'KH':'Kambodscha'
	, 'KI':'Kiribati'
	, 'KM':'Komoren'
	, 'KN':'St. Kitts und Nevis'
	, 'KP':'Nordkorea'
	, 'KR':'SÃ¼dkorea'
	, 'KW':'Kuwait'
	, 'KY':'Kaimaninseln'
	, 'KZ':'Kasachstan'
	, 'LA':'Demokratische Volksrepublik Laos'
	, 'LB':'Libanon'
	, 'LC':'St. Lucia'
	, 'LI':'Liechtenstein'
	, 'LK':'Sri Lanka'
	, 'LR':'Liberia'
	, 'LS':'Lesotho'
	, 'LT':'Litauen'
	, 'LU':'Luxemburg'
	, 'LV':'Lettland'
	, 'LY':'Libyen'
	, 'MA':'Marokko'
	, 'MC':'Monaco'
	, 'MD':'Moldau'
	, 'ME':'Montenegro'
	, 'MF':'St. Martin'
	, 'MG':'Madagaskar'
	, 'MH':'Marshallinseln'
	, 'ML':'Mali'
	, 'MM':'Birma/Myanmar'
	, 'MN':'Mongolei'
	, 'MO':'Macau'
	, 'MP':'NÃ¶rdliche Marianen'
	, 'MQ':'Martinique'
	, 'MR':'Mauretanien'
	, 'MS':'Montserrat'
	, 'MT':'Malta'
	, 'MU':'Mauritius'
	, 'MV':'Malediven'
	, 'MW':'Malawi'
	, 'MX':'Mexiko'
	, 'MY':'Malaysia'
	, 'MZ':'Mosambik'
	, 'NA':'Namibia'
	, 'NC':'Neukaledonien'
	, 'NE':'Niger'
	, 'NF':'Norfolkinsel'
	, 'NG':'Nigeria'
	, 'NI':'Nicaragua'
	, 'NL':'Niederlande'
	, 'NO':'Norwegen'
	, 'NP':'Nepal'
	, 'NR':'Nauru'
	, 'NU':'Niue'
	, 'NZ':'Neuseeland'
	, 'OM':'Oman'
	, 'PA':'Panama'
	, 'PE':'Peru'
	, 'PF':'FranzÃ¶sisch-Polynesien'
	, 'PG':'Papua-Neuguinea'
	, 'PH':'Philippinen'
	, 'PK':'Pakistan'
	, 'PL':'Polen'
	, 'PM':'St. Pierre und Miquelon'
	, 'PN':'Pitcairninseln'
	, 'PR':'Puerto Rico'
	, 'PT':'Portugal'
	, 'PW':'Palau'
	, 'PY':'Paraguay'
	, 'QA':'Katar'
	, 'RE':'RÃ©union'
	, 'RO':'RumÃ¤nien'
	, 'RS':'Serbien'
	, 'RU':'Russland'
	, 'RW':'Ruanda'
	, 'SA':'Saudi-Arabien'
	, 'SB':'Salomonen'
	, 'SC':'Seychellen'
	, 'SD':'Sudan'
	, 'SE':'Schweden'
	, 'SG':'Singapur'
	, 'SH':'St. Helena'
	, 'SI':'Slowenien'
	, 'SJ':'Svalbard und Jan Mayen'
	, 'SK':'Slowakei'
	, 'SL':'Sierra Leone'
	, 'SM':'San Marino'
	, 'SN':'Senegal'
	, 'SO':'Somalia'
	, 'SR':'Suriname'
	, 'SS':'SÃ¼dsudan'
	, 'ST':'SÃ£o TomÃ© und PrÃ­ncipe'
	, 'SV':'El Salvador'
	, 'SX':'St. Martin'
	, 'SY':'Syrien'
	, 'SZ':'Swasiland'
	, 'TC':'Turks- und Caicosinseln'
	, 'TD':'Tschad'
	, 'TF':'FranzÃ¶sische SÃ¼d- und Antarktisgebiete'
	, 'TG':'Togo'
	, 'TH':'Thailand'
	, 'TJ':'Tadschikistan'
	, 'TK':'Tokelau'
	, 'TL':'Timor-Leste'
	, 'TM':'Turkmenistan'
	, 'TN':'Tunesien'
	, 'TO':'Tonga'
	, 'TR':'TÃ¼rkei'
	, 'TT':'Trinidad und Tobago'
	, 'TV':'Tuvalu'
	, 'TW':'Taiwan'
	, 'TZ':'Tansania'
	, 'UA':'Ukraine'
	, 'UG':'Uganda'
	, 'UK':'Vereinigtes KÃ¶nigreich'
	, 'UM':'Kleinere Amerikanische Ãberseeinseln'
	, 'US':'Vereinigte Staaten'
	, 'UY':'Uruguay'
	, 'UZ':'Usbekistan'
	, 'VA':'Heiliger Stuhl/Vatikanstadt'
	, 'VC':'St. Vincent und die Grenadinen'
	, 'VE':'Venezuela'
	, 'VG':'Britische Jungferninseln'
	, 'VI':'Amerikanische Jungferninseln'
	, 'VN':'Vietnam'
	, 'VU':'Vanuatu'
	, 'WF':'Wallis und Futuna'
	, 'WS':'Samoa'
	, 'YE':'Jemen'
	, 'YT':'Mayotte'
	, 'ZA':'SÃ¼dafrika'
	, 'ZM':'Sambia'
	, 'ZW':'Simbabwe'
     };
})(typeof exports === 'undefined' ? this['iso'] = {} : exports);

